version: '3.8'
services: 
    database:
        image: postgres 
        environment: 
            - POSTGRES_DB=blueddit
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
        expose:
            - "5432"